oro_entity_config:
    pmanager:
        field:
            items:
                available_in_template:
                    options:
                        default_value:      true
                        allowed_type:       [string, text, integer, smallint, bigint, boolean, datetime, date, time, float, decimal, money, percent, optionSet, enum, multiEnum, file, image, ref-one, manyToOne]
                    form:
                        type:               choice
                        options:
                            choices:        ['No', 'Yes']
                            empty_value:    false
                            block:          other
                            label:          ibnab.pmanager.entity_config.pdftemplate.field.items.available_in_template
